/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.Sesion;
import modelo.Marcador;
import modelo.Usuario;
import controlador.Registro;
import java.util.ArrayList;
import static vistas.VistaUsuario.chk1;
import static vistas.VistaUsuario.chk10;
import static vistas.VistaUsuario.chk11;
import static vistas.VistaUsuario.chk12;
import static vistas.VistaUsuario.chk13;
import static vistas.VistaUsuario.chk14;
import static vistas.VistaUsuario.chk15;
import static vistas.VistaUsuario.chk16;
import static vistas.VistaUsuario.chk2;
import static vistas.VistaUsuario.chk3;
import static vistas.VistaUsuario.chk4;
import static vistas.VistaUsuario.chk5;
import static vistas.VistaUsuario.chk6;
import static vistas.VistaUsuario.chk7;
import static vistas.VistaUsuario.chk8;
import static vistas.VistaUsuario.chk9;

/**
 *
 * @author patricio
 */
public class VistaCarpetas extends javax.swing.JFrame {

    /**
     * Creates new form VistaCarpetas
     */
    public VistaCarpetas() {
        initComponents();
        this.setLocationRelativeTo(null);
        btConfirmar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCarpeta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        optNoticias = new javax.swing.JRadioButton();
        optEstudio = new javax.swing.JRadioButton();
        optCompras = new javax.swing.JRadioButton();
        optCultura = new javax.swing.JRadioButton();
        optSocial = new javax.swing.JRadioButton();
        optOcio = new javax.swing.JRadioButton();
        btConfirmar = new javax.swing.JButton();
        btVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(211, 244, 239));
        setLocation(new java.awt.Point(15, 15));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Mover a la carpeta...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        optNoticias.setBackground(new java.awt.Color(255, 255, 255));
        bgCarpeta.add(optNoticias);
        optNoticias.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        optNoticias.setText("Noticias");
        optNoticias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optNoticiasMouseClicked(evt);
            }
        });

        optEstudio.setBackground(new java.awt.Color(255, 255, 255));
        bgCarpeta.add(optEstudio);
        optEstudio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        optEstudio.setText("Estudio");
        optEstudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optEstudioMouseClicked(evt);
            }
        });

        optCompras.setBackground(new java.awt.Color(255, 255, 255));
        bgCarpeta.add(optCompras);
        optCompras.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        optCompras.setText("Compras");
        optCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optComprasMouseClicked(evt);
            }
        });

        optCultura.setBackground(new java.awt.Color(255, 255, 255));
        bgCarpeta.add(optCultura);
        optCultura.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        optCultura.setText("Cultura");
        optCultura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optCulturaMouseClicked(evt);
            }
        });

        optSocial.setBackground(new java.awt.Color(255, 255, 255));
        bgCarpeta.add(optSocial);
        optSocial.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        optSocial.setText("Social");
        optSocial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optSocialMouseClicked(evt);
            }
        });

        optOcio.setBackground(new java.awt.Color(255, 255, 255));
        bgCarpeta.add(optOcio);
        optOcio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        optOcio.setText("Ocio");
        optOcio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optOcioMouseClicked(evt);
            }
        });

        btConfirmar.setBackground(new java.awt.Color(255, 255, 255));
        btConfirmar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        btVolver.setBackground(new java.awt.Color(255, 255, 255));
        btVolver.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btVolver.setText("Volver");
        btVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(optOcio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optCultura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optEstudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optNoticias, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(optNoticias)
                .addGap(18, 18, 18)
                .addComponent(optEstudio)
                .addGap(18, 18, 18)
                .addComponent(optCompras)
                .addGap(18, 18, 18)
                .addComponent(optCultura)
                .addGap(18, 18, 18)
                .addComponent(optSocial)
                .addGap(18, 18, 18)
                .addComponent(optOcio)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed

        int idCarpeta;
        if (optNoticias.isSelected()){
            idCarpeta = 1;
        }else if (optEstudio.isSelected()){
            idCarpeta = 2;
        }else if (optCompras.isSelected()){
            idCarpeta = 3;
        }else if (optCultura.isSelected()){
            idCarpeta = 4;
        }else if (optSocial.isSelected()){
            idCarpeta = 5;
        }else if (optOcio.isSelected()){
            idCarpeta = 6;
        }else{
            idCarpeta = 0;
        } 
        
        Registro rg = new Registro();
  
        for (Marcador tmp : Sesion.marcadoresSeleccionados) { //carpetaActiva se llena con los marcadores en VistaUsuario
            rg.moverMarcadorACarpeta(tmp, idCarpeta);
        }
        chk1.setSelected(false);
        chk2.setSelected(false);
        chk3.setSelected(false);
        chk4.setSelected(false);
        chk5.setSelected(false);
        chk6.setSelected(false);
        chk7.setSelected(false);
        chk8.setSelected(false);
        chk9.setSelected(false);
        chk10.setSelected(false);
        chk11.setSelected(false);
        chk12.setSelected(false);
        chk13.setSelected(false);
        chk14.setSelected(false);
        chk15.setSelected(false);
        chk16.setSelected(false);
        dispose();
            
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverActionPerformed
        dispose();        
    }//GEN-LAST:event_btVolverActionPerformed

    private void optNoticiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optNoticiasMouseClicked
        btConfirmar.setEnabled(true);       
    }//GEN-LAST:event_optNoticiasMouseClicked

    private void optEstudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optEstudioMouseClicked
        btConfirmar.setEnabled(true);  
    }//GEN-LAST:event_optEstudioMouseClicked

    private void optComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optComprasMouseClicked
        btConfirmar.setEnabled(true);  
    }//GEN-LAST:event_optComprasMouseClicked

    private void optCulturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optCulturaMouseClicked
        btConfirmar.setEnabled(true);  
    }//GEN-LAST:event_optCulturaMouseClicked

    private void optSocialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optSocialMouseClicked
        btConfirmar.setEnabled(true);  
    }//GEN-LAST:event_optSocialMouseClicked

    private void optOcioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optOcioMouseClicked
        btConfirmar.setEnabled(true);  
    }//GEN-LAST:event_optOcioMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCarpeta;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton optCompras;
    private javax.swing.JRadioButton optCultura;
    private javax.swing.JRadioButton optEstudio;
    private javax.swing.JRadioButton optNoticias;
    private javax.swing.JRadioButton optOcio;
    private javax.swing.JRadioButton optSocial;
    // End of variables declaration//GEN-END:variables
}
