/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.Sesion;
import modelo.Marcador;
import controlador.Registro;
import javax.swing.JOptionPane;

/**
 *
 * @author patricio
 */
public class VistaCarpetas extends javax.swing.JFrame {

    /**
     * Creates new form VistaCarpetas
     */
    public VistaCarpetas() {
        initComponents();
        this.setLocationRelativeTo(null);
        btConfirmar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCarpeta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        optNoticias = new javax.swing.JRadioButton();
        optEstudio = new javax.swing.JRadioButton();
        optCompras = new javax.swing.JRadioButton();
        lblIconoNoticias = new javax.swing.JLabel();
        lblIconoCompras = new javax.swing.JLabel();
        lblIconoEstudio = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btVolver = new javax.swing.JButton();
        btConfirmar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblIconoSocial = new javax.swing.JLabel();
        optSocial = new javax.swing.JRadioButton();
        optCultura = new javax.swing.JRadioButton();
        lblIconoCultura = new javax.swing.JLabel();
        lblIconoOcio = new javax.swing.JLabel();
        optOcio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mover a carpeta");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(15, 15));
        setPreferredSize(new java.awt.Dimension(395, 457));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 0, 153));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-add-folder-64.png"))); // NOI18N
        lblTitulo.setText("MOVER A CARPETA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        optNoticias.setBackground(new java.awt.Color(255, 255, 255));
        bgCarpeta.add(optNoticias);
        optNoticias.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        optNoticias.setText("Noticias");
        optNoticias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optNoticiasMouseClicked(evt);
            }
        });

        optEstudio.setBackground(new java.awt.Color(255, 255, 255));
        bgCarpeta.add(optEstudio);
        optEstudio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        optEstudio.setText("Estudio");
        optEstudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optEstudioMouseClicked(evt);
            }
        });

        optCompras.setBackground(new java.awt.Color(255, 255, 255));
        bgCarpeta.add(optCompras);
        optCompras.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        optCompras.setText("Compras");
        optCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optComprasMouseClicked(evt);
            }
        });

        lblIconoNoticias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-news-64.png"))); // NOI18N
        lblIconoNoticias.setText("jLabel1");

        lblIconoCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-sale-price-tag-64.png"))); // NOI18N

        lblIconoEstudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-student-male-64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(optNoticias, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblIconoNoticias, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(optEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIconoEstudio)
                        .addGap(37, 37, 37)))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconoCompras)
                    .addComponent(optCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIconoEstudio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIconoCompras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblIconoNoticias, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(optEstudio)
                        .addComponent(optCompras))
                    .addComponent(optNoticias))
                .addGap(143, 143, 143))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btVolver.setBackground(new java.awt.Color(255, 255, 255));
        btVolver.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btVolver.setForeground(new java.awt.Color(51, 0, 153));
        btVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-return-32.png"))); // NOI18N
        btVolver.setText("Volver");
        btVolver.setMinimumSize(new java.awt.Dimension(121, 27));
        btVolver.setPreferredSize(new java.awt.Dimension(121, 27));
        btVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverActionPerformed(evt);
            }
        });

        btConfirmar.setBackground(new java.awt.Color(255, 255, 255));
        btConfirmar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btConfirmar.setForeground(new java.awt.Color(51, 0, 153));
        btConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-approval-32.png"))); // NOI18N
        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblIconoSocial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-technical-support-64.png"))); // NOI18N

        optSocial.setBackground(new java.awt.Color(255, 255, 255));
        bgCarpeta.add(optSocial);
        optSocial.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        optSocial.setText("Social");
        optSocial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optSocialMouseClicked(evt);
            }
        });

        optCultura.setBackground(new java.awt.Color(255, 255, 255));
        bgCarpeta.add(optCultura);
        optCultura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        optCultura.setText("Cultura");
        optCultura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optCulturaMouseClicked(evt);
            }
        });

        lblIconoCultura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-library-64.png"))); // NOI18N

        lblIconoOcio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-retro-tv-64.png"))); // NOI18N

        optOcio.setBackground(new java.awt.Color(255, 255, 255));
        bgCarpeta.add(optOcio);
        optOcio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        optOcio.setText("Ocio");
        optOcio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optOcioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(optSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(optCultura, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblIconoSocial)
                        .addGap(53, 53, 53)
                        .addComponent(lblIconoCultura)))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconoOcio)
                    .addComponent(optOcio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconoOcio)
                    .addComponent(lblIconoCultura)
                    .addComponent(lblIconoSocial))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optCultura)
                    .addComponent(optOcio)
                    .addComponent(optSocial))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverActionPerformed
        dispose();
    }//GEN-LAST:event_btVolverActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed

        int idCarpeta;
        if (optNoticias.isSelected()){
            idCarpeta = 1;
        }else if (optEstudio.isSelected()){
            idCarpeta = 2;
        }else if (optCompras.isSelected()){
            idCarpeta = 3;
        }else if (optCultura.isSelected()){
            idCarpeta = 4;
        }else if (optSocial.isSelected()){
            idCarpeta = 5;
        }else if (optOcio.isSelected()){
            idCarpeta = 6;
        }else{
            idCarpeta = 0;
        }

        Registro rg = new Registro();

        for (Marcador tmp : Sesion.marcadoresSeleccionados) { //carpetaActiva se llena con los marcadores en VistaUsuario
            rg.moverMarcadorACarpeta(tmp, idCarpeta);
        }
        
        JOptionPane.showMessageDialog(this, "Se movieron los marcadores a la carpeta seleccionada", "Marcadores a carpeta", JOptionPane.INFORMATION_MESSAGE);
        
        VistaUsuario.chk1.setSelected(false);
        VistaUsuario.chk2.setSelected(false);
        VistaUsuario.chk3.setSelected(false);
        VistaUsuario.chk4.setSelected(false);
        VistaUsuario.chk5.setSelected(false);
        VistaUsuario.chk6.setSelected(false);
        VistaUsuario.chk7.setSelected(false);
        VistaUsuario.chk8.setSelected(false);
        VistaUsuario.chk9.setSelected(false);
        VistaUsuario.chk10.setSelected(false);
        VistaUsuario.chk11.setSelected(false);
        VistaUsuario.chk12.setSelected(false);
        VistaUsuario.chk13.setSelected(false);
        VistaUsuario.chk14.setSelected(false);
        VistaUsuario.chk15.setSelected(false);
        VistaUsuario.chk16.setSelected(false);
        dispose();

    }//GEN-LAST:event_btConfirmarActionPerformed

    private void optOcioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optOcioMouseClicked
        btConfirmar.setEnabled(true);
    }//GEN-LAST:event_optOcioMouseClicked

    private void optSocialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optSocialMouseClicked
        btConfirmar.setEnabled(true);
    }//GEN-LAST:event_optSocialMouseClicked

    private void optCulturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optCulturaMouseClicked
        btConfirmar.setEnabled(true);
    }//GEN-LAST:event_optCulturaMouseClicked

    private void optComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optComprasMouseClicked
        btConfirmar.setEnabled(true);
    }//GEN-LAST:event_optComprasMouseClicked

    private void optEstudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optEstudioMouseClicked
        btConfirmar.setEnabled(true);
    }//GEN-LAST:event_optEstudioMouseClicked

    private void optNoticiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optNoticiasMouseClicked
        btConfirmar.setEnabled(true);
    }//GEN-LAST:event_optNoticiasMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCarpeta;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblIconoCompras;
    private javax.swing.JLabel lblIconoCultura;
    private javax.swing.JLabel lblIconoEstudio;
    private javax.swing.JLabel lblIconoNoticias;
    private javax.swing.JLabel lblIconoOcio;
    private javax.swing.JLabel lblIconoSocial;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton optCompras;
    private javax.swing.JRadioButton optCultura;
    private javax.swing.JRadioButton optEstudio;
    private javax.swing.JRadioButton optNoticias;
    private javax.swing.JRadioButton optOcio;
    private javax.swing.JRadioButton optSocial;
    // End of variables declaration//GEN-END:variables
}
